# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_kernel <- function(X, X_new = NULL, kernel = "gaussian", rho = 0, n_threads = 4L) {
    .Call(`_FastKRR_make_kernel`, X, X_new, kernel, rho, n_threads)
}

nystrom <- function(K, y, m, lambda, n_threads = 4L) {
    .Call(`_FastKRR_nystrom`, K, y, m, lambda, n_threads)
}

nystrom_kernel <- function(K, m_in = NULL, n_threads = 4L) {
    .Call(`_FastKRR_nystrom_kernel`, K, m_in, n_threads)
}

pchol <- function(A, y, lambda, m = NULL, eps = 1e-6, verbose = TRUE) {
    .Call(`_FastKRR_pchol`, A, y, lambda, m, eps, verbose)
}

pchol_kernel <- function(A, m = NULL, eps = 1e-6, verbose = TRUE) {
    .Call(`_FastKRR_pchol_kernel`, A, m, eps, verbose)
}

rff <- function(X, y, W, b, lambda, n_threads = 4L) {
    .Call(`_FastKRR_rff`, X, y, W, b, lambda, n_threads)
}

make_Z <- function(X, W, b, n_threads = 4L) {
    .Call(`_FastKRR_make_Z`, X, W, b, n_threads)
}

get_num_procs <- function() {
    .Call(`_FastKRR_get_num_procs`)
}

solve_chol <- function(A, b) {
    .Call(`_FastKRR_solve_chol`, A, b)
}

SOLVE_sympd <- function(A, b) {
    .Call(`_FastKRR_SOLVE_sympd`, A, b)
}

